In [31]:
import numpy as np
np.random.seed(42) #固定随机种子，实验可复现
#输入数据，3个特征
X=2*np.random.rand(100,3).astype(np.float32) #生成100行3列的随机数据，范围在0到2之间
#真实的权重
true_W=np.array([[3],[2],[-1.5]]).astype(np.float32)
#真实标签列向量，再加上随机噪声
y=X.dot(true_W)+np.random.randn(100,1) 

In [32]:
#嵌套列表[[3.], [2.], [-1.5]]：
# 每一个内层[]代表数组的一行，每行仅 1 个元素，
# 因此是3 行 1 列的二维结构；
true_W

array([[ 3. ],
       [ 2. ],
       [-1.5]], dtype=float32)

In [33]:
X.shape
X.shape[1] #特征数量，即列数

3

In [34]:
#初始化参数
W=np.random.randn(X.shape[1],1).astype(np.float32) #随机生成3行1列的权重矩阵
W

array([[ 0.07580456],
       [-0.6771617 ],
       [ 0.9751197 ]], dtype=float32)

In [37]:
#超参数
learning_rate=0.001 #学习率
n_iterations=10000 #迭代次数
m=len(y)#样本数量，即行数

In [27]:
print('x.shape:',X.shape)
print('y.shape:',y.shape)
print('W.shape:',W.shape)

x.shape: torch.Size([100, 3])
y.shape: torch.Size([100, 1])
W.shape: (3, 1)


In [ ]:
#纯批量梯度下降BGD：每次参数更新以全部的训练样本
#loss(w)=1/2m*∑(y(i)-X(i)·W)²，对损失函数求导
#gradients=-1/m * X.T@(y-X@W)
for iteration in range(n_iterations):
    gradients=-1/m * X.T@(y-X@W) #计算梯度
    W=W-learning_rate*gradients #更新权重
    if iteration % 50 == 0:
        loss=np.mean((y - X@W) ** 2) / 2  #计算损失
        print(f"iteration {iteration}, loss {loss:.4f}")

iteration 0, loss 6.3307
iteration 50, loss 5.3880
iteration 100, loss 4.6842
iteration 150, loss 4.1534
iteration 200, loss 3.7479
iteration 250, loss 3.4335
iteration 300, loss 3.1855
iteration 350, loss 2.9860
iteration 400, loss 2.8223
iteration 450, loss 2.6849
iteration 500, loss 2.5673
iteration 550, loss 2.4645
iteration 600, loss 2.3731
iteration 650, loss 2.2904
iteration 700, loss 2.2147
iteration 750, loss 2.1446
iteration 800, loss 2.0791
iteration 850, loss 2.0174
iteration 900, loss 1.9589
iteration 950, loss 1.9034
iteration 1000, loss 1.8503
iteration 1050, loss 1.7996
iteration 1100, loss 1.7510
iteration 1150, loss 1.7043
iteration 1200, loss 1.6594
iteration 1250, loss 1.6163
iteration 1300, loss 1.5748
iteration 1350, loss 1.5348
iteration 1400, loss 1.4963
iteration 1450, loss 1.4592
iteration 1500, loss 1.4235
iteration 1550, loss 1.3891
iteration 1600, loss 1.3559
iteration 1650, loss 1.3239
iteration 1700, loss 1.2930
iteration 1750, loss 1.2633
iteration 1800,

In [39]:
print("训练权重：\n",W)
print("真实权重：\n",true_W)

训练权重：
 [[ 3.00338196]
 [ 1.82172396]
 [-1.22048784]]
真实权重：
 [[ 3. ]
 [ 2. ]
 [-1.5]]


In [45]:
import torch
import torch.nn as nn

#1.准备数据
torch.manual_seed(42) #固定随机种子，实验可复现
X=2*torch.rand(100,3).float() #生成100行3列的随机数据，数值[0,2)
true_W=torch.tensor([[3],[2],[-1.5]]) #真实权重
#生成y时不加偏置 Y=WX+noise,没有偏置项
y=X@true_W+torch.randn(100,1).float() *0.5 #真实标签列向量，再加上随机噪声


In [46]:
#2.定义线性模型
in_features=3#输入特征数量
out_features=1#输出特征数量
bias=False #不使用偏置项
#nn.Linear是PyTorch中线性层,是一个简单的线性模型，
model=nn.Linear(in_features,out_features,bias=bias) 

In [ ]:
#3.定义损失函数和优化器
criterion=nn.MSELoss() #均方误差损失函数
optimizer=torch.optim.SGD(model.parameters(),lr=0.1) #随机梯度下降优化器
# 模型内置了可训练的参数weight和bias（如果bias=True的话），
# 不需要手动定义权重W，也不用手动更新参数

In [51]:
# 4.训练模型：小批量梯度下降（SGD）每次参数更新以一个训练样本，兼顾计算和并行
for epoch in range(500):
    #前向传播 计算预测值和损失
    y_pred=model(X)
    loss=criterion(y_pred,y)
    #反向传播和优化 标准的梯度清零、反向传播、参数更新步骤
    optimizer.zero_grad() 
    loss.backward() 
    optimizer.step() 

    if epoch % 100 == 0:
        print(f"epoch {epoch}, loss {loss.item():.4f}") #loss是一个张量，用item()获取数值

epoch 0, loss 0.2213
epoch 100, loss 0.2213
epoch 200, loss 0.2213
epoch 300, loss 0.2213
epoch 400, loss 0.2213


In [50]:
#5.训练结果
print("训练权重：\n",model.weight.data.flatten().tolist()) #model.weight是一个张量，flatten()将其展平为一维数组.
print("真实权重：\n",true_W.flatten().tolist())

训练权重：
 [2.995447874069214, 1.9864319562911987, -1.4186646938323975]
真实权重：
 [3.0, 2.0, -1.5]
